name: Serverless CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'pnpm'
          node-version: '12'
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm build
      - name: Deploy project
        uses: byteinspire/cloud-project-deployer-action@v1
        with:
          service-id: '${{ secrets.SERVICE_ID }}'
          token: '${{ secrets.ACCESS_TOKEN }}'
